<?php
/*
Plugin Name: Offline Pages
Plugin URI: http://codiumlabs.com/offline-wordpress/
File Name:   index.php
Description: This plugin allows you to cache and browse your entire WordPress site on iPad, iPhone, or Mac while having no network connection whatsoever. It works in tandem with <a href="http://codiumlabs.com/">Offline Pages Pro</a> app to synchronize your WordPress articles with device storage and deliver unique offline browsing experience, not achievable any other way. Visit Offline settings page to learn more. 
Author: Codium Labs LLC
Version: 1.0.0
Author URI: http://codiumlabs.com/
*/

/*
 * Unique content-type string reserved for Offline Pages rules documents. In most contexts,
 * it is acceptable to use text/xml instead. 
 */
define('RULES_CONTENT_TYPE', 'application/vnd.offlinepages.rules+xml');

global $wp_version;
if (version_compare($wp_version, "3.1", "<")) {
	exit('This plugin requires WordPress 3.1 or newer. <a href="http://codex.wordpress.org/Upgrading_WordPress">Please update!</a>');
}

add_action('wp_head', 'opwp_print_head');
add_action('wp_ajax_opwp_rules', 'opwp_print_rules');
add_action('wp_ajax_nopriv_opwp_rules', 'opwp_print_rules');

register_activation_hook( __FILE__, 'opwp_set_defaults');

if (is_admin()) {
	add_action('admin_menu', 'opwp_admin_menu');
    add_action('admin_init', 'opwp_register_settings' );
}


/*
 * Prints <link> element referencing rules document auto-generated by this plugin.
 */
function opwp_print_head() {
	echo '<link rel="offlinepages-rules" type="' . RULES_CONTENT_TYPE . '" href="' .
		admin_url('admin-ajax.php').'?action=opwp_rules' . '" />' . PHP_EOL;
}


/*
 * Prints the rules document reflecting user preferences and specifics of this WordPress
 * installation.
 */
function opwp_print_rules()
{
	header('Content-Type: ' . RULES_CONTENT_TYPE);
	echo '<?xml version="1.0" encoding="UTF-8"?>' . PHP_EOL;
	echo '<!DOCTYPE rules PUBLIC "-//CODIUMLABS//DTD RULES 1.0//EN" "http://codiumlabs.com/dtd/rules-1.0.dtd">' . PHP_EOL;
	
	/*
	 * Admin area, login, logout, feeds should never be synchronized.
	 */
	echo '<rules domain="' . $_SERVER['SERVER_NAME'] . '">' . PHP_EOL;
	echo '<rule scope="pages" match="/wp-admin/" block="true" />' . PHP_EOL;
	echo '<rule scope="pages" match="/wp-(login|logout).php" block="true" />' . PHP_EOL;
	echo '<rule scope="pages" match="[?&amp;](replytocom|feed)=" block="true" />' . PHP_EOL;
	echo '<rule scope="pages" match="/feed/?$" block="true" />' . PHP_EOL;
	
	/*
	 * Exclude any pages outside of this WordPress installation (only makes sense when
	 * WordPress is installed in a subdirectory.
	 */
	if (!get_option('opwp_allow_external_pages')) {
		$home_url = home_url();
		if (substr($home_url, -1) != '/') {
			$home_url .= '/';
		}
		if (substr($home_url, 0, 5) == 'http:') {
			$home_url = substr($home_url, 5);
		} elseif (substr($home_url, 0, 6) == 'https:') {
			$home_url = substr($home_url, 6);
		}
		echo '<rule scope="pages" block="true" />' . PHP_EOL;
		echo '<rule scope="pages" match="' . preg_quote($home_url) . '?" allow="true" />' . PHP_EOL;
	}
	
	/*
	 * Block category index pages unless user wants them.
	 */
	if (!get_option('opwp_allow_category_pages')) {
		echo '<rule scope="pages" match="[?&amp;]category_name=" block="true" />' . PHP_EOL;
		$category_base = get_option('category_base');
		if (!$category_base) {
			$category_base = 'category';
		}
		if (substr($category_base, 0, 1) != '/')
			$category_base = '/' . $category_base;
		if (substr($category_base, -1) != '/')
			$category_base = $category_base . '/';
		echo '<rule scope="pages" match="' . preg_quote($category_base) . '" block="true" />' . PHP_EOL;
	}
	
	/*
	 * Block tag index pages unless user wants them.
	 */
	if (!get_option('opwp_allow_tag_pages')) {
		echo '<rule scope="pages" match="[?&amp;]tag=" block="true" />' . PHP_EOL;
		$tag_base = get_option('tag_base');
		if (!$tag_base) {
			$tag_base = 'tag';
		}
		if (substr($tag_base, 0, 1) != '/')
			$tag_base = '/' . $tag_base;
		if (substr($tag_base, -1) != '/')
			$tag_base = $tag_base . '/';
		echo '<rule scope="pages" match="' . preg_quote($tag_base) . '" block="true" />' . PHP_EOL;
	}
	
	/*
	 * Block author index pages unless user wants them.
	 */
	if (!get_option('opwp_allow_author_pages')) {
		echo '<rule scope="pages" match="[?&amp;]author=" block="true" />' . PHP_EOL;
		echo '<rule scope="pages" match="/author/" block="true" />' . PHP_EOL;
	}
	
	/*
	 * Finally, output any custom rules verbatim.
	 */
	$rules = get_option('opwp_custom_rules');
	if ($rules) {
		echo $rules . PHP_EOL;
	}
	echo '</rules>' . PHP_EOL;
	exit;
}


/*
 * Displays settings page.
 */
function opwp_settings_page() {
	$opwp_custom_rules = get_option('opwp_custom_rules'); 
	$opwp_allow_external_pages = get_option('opwp_allow_external_pages');
	$opwp_allow_category_pages = get_option('opwp_allow_category_pages');
	$opwp_allow_tag_pages = get_option('opwp_allow_tag_pages');
	$opwp_allow_author_pages = get_option('opwp_allow_author_pages');
	?>
<div class="wrap">
<div id="icon-options-general" class="icon32"><br></div>
<h2>Offline</h2>
<form method="post" action="options.php">
	<?php settings_fields('offline-pages'); ?>
	<p>This plugin is designed to work in tandem with Offline Pages series of iOS and Mac apps &mdash; Offline Pages, Offline Pages Pro, Offline Kiosk, Offline Forms, as well as any custom-build apps on same platform. This plugin does not offer any useful functionality without the apps.</p>
	<p>The purpose of the plugin is to fine-tune sync parameters in the mobile app for best performance with this WordPress installation. The plugin is required if you want to allow offline access to your WordPress site while using an AJAX theme. It is optional, but still recommended with non-AJAX themes. Refer to Offline Pages <a href="http://codiumlabs.com/api">documentation</a> or <a href="http://codiumlabs.com/support">contact support</a> for website-specific instructions.</p>
	<h3>Offline Settings</h3>
    <table class="form-table">
        <tr valign="top">
	        <th scope="row">
	        	Synchronization Settings
	        </th>
			<td>
				<fieldset>
					<legend class="screen-reader-text"><span>Scope settings</span></legend>
					<label for="opwp_allow_category_pages">
					<input name="opwp_allow_category_pages" type="checkbox" id="opwp_allow_category_pages" <?php if ($opwp_allow_category_pages) echo 'checked="checked"' ?>>
					Download category index pages</label>
					<br>
					<label for="opwp_allow_tag_pages">
					<input name="opwp_allow_tag_pages" type="checkbox" id="opwp_allow_tag_pages" <?php if ($opwp_allow_tag_pages) echo 'checked="checked"' ?>>
					Download tag index pages</label>
					<br>
					<label for="opwp_allow_author_pages">
					<input name="opwp_allow_author_pages" type="checkbox" id="opwp_allow_author_pages" <?php if ($opwp_allow_author_pages) echo 'checked="checked"' ?>>
					Download author index pages</label>
					<br>
					<label for="opwp_allow_external_pages">
					<input name="opwp_allow_external_pages" type="checkbox" id="opwp_allow_external_pages" <?php if ($opwp_allow_external_pages) echo 'checked="checked"' ?>>
					Download pages on <strong><?php echo $_SERVER['SERVER_NAME'] ?></strong> outside of WordPress directory (not recommended)</label>
				</fieldset>
			</td>
		</tr>
        <tr valign="top">
	        <th scope="row">
	        	Custom Rules
	        </th>
			<td>
				<p>
					<textarea name="opwp_custom_rules" rows="10" cols="50" id="opwp_custom_rules" class="large-text code"><?php echo $opwp_custom_rules; ?></textarea>
				</p>
				<p>Type one or more &lt;rule&gt; elements only. DOCTYPE and enclosing &lt;rules&gt; element will be added automatically. Careful - no XML validation is performed and your code is written verbatim in the aggregated rules document!</p>
				<p>Document Type Definition: <a href="http://codiumlabs.com/dtd/rules-1.0.dtd">http://codiumlabs.com/dtd/rules-1.0.dtd</a></p>
				<p>Format Documentation: <a href="http://codiumlabs.com/api">http://codiumlabs.com/api</a></p>
				<p>Example:</p>
				<p><code>&lt;!--<br>Skip articles with URL containing the word humor:  <br>--&gt;<br>
						&lt;rule match=&quot;humor&quot; block=&quot;true&quot; /&gt;</code>
					</p>
			</td>
        </tr>
	</table>
    <p class="submit">
    <input type="submit"  class="button-primary" value="Save Changes" />
    </p>
</form>
</div>
</div>
	<?php
}


/*
 * Registers all settings used by this plugin.
 */
function opwp_register_settings() {
	register_setting('offline-pages', 'opwp_custom_rules');
	register_setting('offline-pages', 'opwp_allow_external_pages');
	register_setting('offline-pages', 'opwp_allow_category_pages');
	register_setting('offline-pages', 'opwp_allow_tag_pages');
	register_setting('offline-pages', 'opwp_allow_author_pages');
}


/*
 * Sets default values for plugin settings. All remaining settings retain their
 * default state (no).
 */
function opwp_set_defaults() {
	add_option('opwp_allow_category_pages', 'yes');
	add_option('opwp_allow_tag_pages', 'yes');
	add_option('opwp_allow_author_pages', 'yes');
}


/*
 * Adds the menu item to Admin area.
 */
function opwp_admin_menu() {
    if (!current_user_can('manage_options'))  {
        wp_die('You do not have sufficient permissions to access this page.');
    }
	add_options_page('Offline', 'Offline', 'administrator', 'offline-pages', 'opwp_settings_page');
}
